Migra do HoneyBadger para o Sentry
vnda/vnda-tracker pull request #114
Opened 2021-03-16 21:27 UTC by davipmesquita

2021-03-17 13:10 UTC, rafaelss requested changes

2021-03-17 13:10 UTC, rafaelss commented on Gemfile
>  gem 'honeybadger', '3.3.1'
precisa remover essa gem

2021-03-17 13:10 UTC, rafaelss commented on spec/services/correios_spec.rb
> +    end
não precisa desse teste

2021-03-17 13:10 UTC, rafaelss commented on spec/services/correios_spec.rb
> +    end
não precisa desse teste

2021-03-17 13:18 UTC, davipmesquita commented on Gemfile
>  gem 'honeybadger', '3.3.1'
@rafaelss eu precisei colocar a versão mais recente dessa gem para que a versão mais recente do Sentry funcionasse (não desse erro no `bin/bundle install`

Se eu usar ao invés da gem Sentry a gem Raven poderia manter a versão antiga do Faraday

2021-03-17 13:19 UTC, rafaelss commented on Gemfile
>  gem 'honeybadger', '3.3.1'
estou falando da gem `honeybadger`

2021-03-17 13:20 UTC, davipmesquita commented on spec/services/correios_spec.rb
> +    end
@rafaelss a ausência de testes para ver se o Sentry ou HoneyBadger eram chamados foi um dos motivos dos erros HTTP não estarem sendo pegos pelos rescue durante os requests

Queria ter apenas um teste pelo menos funcionando para ter certeza de que estava entrando nos rescue e chamando o Sentry

2021-03-17 13:20 UTC, davipmesquita commented on Gemfile
>  gem 'honeybadger', '3.3.1'
Ah, certo, vou remover ela quando terminar de tirar o HoneyBadger de outras partes do projeto

2021-03-18 12:17 UTC, davipmesquita commented on spec/services/correios_spec.rb
> +    end
teste removido

2021-03-18 13:06 UTC, rafaelss requested changes

2021-03-18 13:07 UTC, rafaelss commented
@davipmesquita precisamos adicionar esse step no deployment de production

https://github.com/vnda/checkout/blob/4406ded4508f1aff5a3b998489427b60976ffbf5/.github/workflows/production.yml#L17-L22
https://github.com/vnda/vnda-tracker/blob/927da2b750d6dc60da58d138e636ed6ede5ae98a/.circleci/config.yml#L67-L70

2021-03-18 13:08 UTC, davipmesquita commented on app/services/correios.rb
> +      Sentry.capture_exception(e)
Alteração feita

2021-03-18 18:02 UTC, rafaelss requested changes

2021-03-18 18:02 UTC, rafaelss commented on .circleci/config.yml
> +            heroku config:set SENTRY_RELEASE=${{ steps.release_version.outputs.tag }} -a vnda-checkout
```suggestion
            heroku config:set APP_REVISION=$CIRCLE_TAG -a vnda-tracker
```

2021-03-18 18:35 UTC, davipmesquita commented on .circleci/config.yml
> +            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
entrada `env:` removida

2021-03-18 18:36 UTC, davipmesquita commented on .circleci/config.yml
> +            heroku config:set SENTRY_RELEASE=${{ steps.release_version.outputs.tag }} -a vnda-checkout
Alteração feita

2021-03-19 20:15 UTC, rafaelss approved these changes

2021-03-19 20:15 UTC, merged