Add Bling integration
vnda/vnda-tracker pull request #117
Opened 2021-04-09 15:56 UTC by davipmesquita

2021-04-12 13:13 UTC, cotelha requested changes

2021-04-12 13:13 UTC, cotelha commented on db/migrate/20210409131130_add_bling_to_shops.rb
> +    add_column :shops, :bling_enabled, :boolean
```suggestion
    add_column :shops, :bling_enabled, :boolean, default:false
```

2021-04-12 13:25 UTC, davipmesquita commented on db/migrate/20210409131130_add_bling_to_shops.rb
> +    add_column :shops, :bling_enabled, :boolean
Alteração feita

2021-04-23 17:38 UTC, fdc263 commented on db/schema.rb
> +    t.boolean "bling_enabled"
```suggestion
    t.boolean "bling_enabled", default: false
```

2021-04-23 19:07 UTC, davipmesquita commented on db/schema.rb
> +    t.boolean "bling_enabled"
Certo, fiz esse ajuste já

2021-04-26 21:04 UTC, fdc263 requested changes

2021-04-26 21:04 UTC, fdc263 commented on config/locales/pt-BR.yml
> +        bling_status_in_transit: 'Situação no Bling para pedidos em trânsito'
```suggestion
        bling_status_in_transit: 'Situação no Bling equivalente a em trânsito'
```

2021-04-26 21:04 UTC, fdc263 commented on config/locales/pt-BR.yml
> +        bling_status_delivered: 'Situação no Bling para pedidos entregues'
```suggestion
        bling_status_delivered: 'Situação no Bling equivalente a entregue'
```

2021-04-26 21:04 UTC, fdc263 commented on db/migrate/20210409131130_add_bling_to_shops.rb
> +    add_column :shops, :bling_status_delivered, :string
faz a alteração em bulk

2021-04-26 21:04 UTC, fdc263 commented on spec/services/bling_spec.rb
> +              'User-Agent' => 'postagem/dev'
```suggestion
              'User-Agent' => 'tracker/dev'
```

2021-04-26 21:04 UTC, fdc263 commented on spec/services/vnda/hub_spec.rb
> +            'User-Agent' => 'postagem/dev'
```suggestion
            'User-Agent' => 'tracker/dev'
```

2021-04-26 21:06 UTC, davipmesquita commented on app/services/vnda/hub.rb
> +        'User-Agent' => 'postagem/' \
Erro meu ao puxar o código do postagem, vou trocar para `tracker`

2021-04-26 21:11 UTC, davipmesquita commented on config/locales/pt-BR.yml
> +        bling_status_in_transit: 'Situação no Bling para pedidos em trânsito'
Alterado

2021-04-26 21:11 UTC, davipmesquita commented on config/locales/pt-BR.yml
> +        bling_status_delivered: 'Situação no Bling para pedidos entregues'
Alterado

2021-04-26 21:12 UTC, davipmesquita commented on spec/services/bling_spec.rb
> +              'User-Agent' => 'postagem/dev'
Alterado

2021-04-26 21:12 UTC, davipmesquita commented on spec/services/vnda/hub_spec.rb
> +            'User-Agent' => 'postagem/dev'
Alterado

2021-04-27 12:36 UTC, davipmesquita commented on db/migrate/20210409131130_add_bling_to_shops.rb
> +    add_column :shops, :bling_status_delivered, :string
Alteração feita

2021-04-27 12:40 UTC, davipmesquita commented on app/services/vnda/hub.rb
> +    API_TOKEN = ENV['API_TOKEN']
@fdc263 Aqui, se eu altero e deixo o `HUB_TOKEN` para ser setado no `before` do `hub_spec`, o teste não funciona, pois ele carrega a classe e o valor de `HUB_TOKEN` antes de rodar o `before`.

O que é melhor nesse caso?
a) Setar o `HUB_TOKEN` no `.env.test` ao invés de no `before`
b) Chamar `ENV['HUB_TOKEN']` direto ao invés de como constante no `headers` de `hub.rb`

2021-04-27 13:18 UTC, fdc263 commented on app/services/vnda/hub.rb
> +    API_TOKEN = ENV['API_TOKEN']
Pode usar `before { stub_const('Vnda::Hub::HUB_TOKEN', 'xxx' }` para fixar um valor nas specs sem precisar alterar o ENV.

2021-04-27 16:14 UTC, fdc263 requested changes

2021-04-27 16:14 UTC, fdc263 commented on spec/services/bling_spec.rb
> +
Já que usou para um, usa para os outros.

```suggestion
    stub_const('Vnda::Hub::HUB_SCHEME', 'https')
    stub_const('Vnda::Hub::HUB_HOST', 'hub.vnda.com.br')

```

2021-04-27 16:14 UTC, fdc263 commented on spec/services/bling_spec.rb
> +  end
Usando stub_cons não precisa disso

2021-04-27 16:14 UTC, fdc263 commented on spec/services/vnda/hub_spec.rb
> +
mesma coisa que no outro arquivo

2021-04-27 16:14 UTC, fdc263 commented on spec/services/vnda/hub_spec.rb
> +    end
O after deve ser depois do before. Mas migrando para stub_const nem será necessário.

2021-04-27 16:18 UTC, davipmesquita commented on spec/services/bling_spec.rb
> +
Alteração feita

2021-04-27 16:18 UTC, davipmesquita commented on spec/services/bling_spec.rb
> +  end
removido

2021-04-27 16:18 UTC, davipmesquita commented on spec/services/vnda/hub_spec.rb
> +
Alteração feita

2021-04-27 16:18 UTC, davipmesquita commented on spec/services/vnda/hub_spec.rb
> +    end
Certo, removido

2021-04-28 12:50 UTC, fdc263 approved these changes

2021-04-28 12:51 UTC, merged