Adiciona integração com a Frenet
vnda/vnda-tracker pull request #141
Opened 2021-07-30 20:57 UTC by davipmesquita

https://trello.com/c/4k9lK9hw/13037-integra%C3%A7%C3%A3o-frenet-tracker

2021-08-17 17:32 UTC, fdc263 requested changes

2021-08-17 17:32 UTC, fdc263 commented on app/models/tracking.rb
> +      return self.tracker_url ||= Frenet.new(shop).tracking_url
precisa de cobertura de teste aqui

2021-08-17 17:32 UTC, fdc263 commented on app/services/frenet/shipping_info.rb
> +      raise InvalidShippingInfoError, 'Shipping info not found for this order'
teste?

2021-08-17 17:32 UTC, fdc263 commented on app/services/frenet/handler.rb
> +      response.body
Poderia já retornar o HASH assim como o anterior.

```suggestion
      JSON.parse(response.body)
```

2021-08-17 17:32 UTC, fdc263 commented on app/services/frenet/tracker.rb
> +      hash = JSON.parse(json)
```suggestion
```

2021-08-17 17:32 UTC, fdc263 commented on app/services/frenet/shipping_info.rb
> +      raise PackageNotFound, "Package #{package_code} not found"
Se retornar o pacote certamente o shipping_label estará preenchido

```suggestion      
      shipping_label = Vnda::Package.new(@shop).get(package_code)&.dig('shipping_label')
      raise PackageNotFound, "Package #{package_code} not found" unless shipping_label
      
      service_code(shipping_label)
```

2021-08-17 17:32 UTC, fdc263 commented on app/services/frenet/shipping_info.rb
> +      return info['ServiceCode'] if info
```suggestion
      result&.each do |service|
        return service['ServiceCode'] if service['ServiceDescription'] == service_name
      end
```

2021-08-17 19:07 UTC, davipmesquita commented on app/models/tracking.rb
> +      return self.tracker_url ||= Frenet.new(shop).tracking_url
Teste adicionado

2021-08-17 19:09 UTC, davipmesquita commented on app/services/frenet/shipping_info.rb
> +      raise InvalidShippingInfoError, 'Shipping info not found for this order'
Esses casos estão sendo testados aqui:
https://github.com/vnda/vnda-tracker/pull/141/files#diff-3bd34597e5410a69de198e8748cccfd1284d6c9c667b4095633e411180d86198R318
https://github.com/vnda/vnda-tracker/pull/141/files#diff-3bd34597e5410a69de198e8748cccfd1284d6c9c667b4095633e411180d86198R359

Precisa de algum refatoramento, talvez algo como colocar o raise depois de tudo e no rescue não fazer nada?

2021-08-17 19:11 UTC, davipmesquita commented on app/services/frenet/handler.rb
> +      response.body
Alteração feita

2021-08-17 19:11 UTC, davipmesquita commented on app/services/frenet/tracker.rb
> +      hash = JSON.parse(json)
Alteração feita

2021-08-17 19:30 UTC, davipmesquita commented on app/services/frenet/shipping_info.rb
> +      raise PackageNotFound, "Package #{package_code} not found"
Ok, alteração feita

2021-08-17 19:39 UTC, davipmesquita commented on app/services/frenet/shipping_info.rb
> +      return info['ServiceCode'] if info
Interessante essa alteração, foi feita

2021-08-17 19:50 UTC, davipmesquita commented on app/services/frenet/shipping_info.rb
> +      raise InvalidShippingInfoError, 'Shipping info not found for this order'
Teste adicionado para essa linha

2021-08-18 21:53 UTC, fdc263 approved these changes

2021-08-18 21:53 UTC, merged