Adiciona cache no retorno da api
vnda/vnda-tracker pull request #67
Opened 2020-09-08 14:41 UTC by cotelha

https://trello.com/c/nAZHa9Dq

2020-09-08 14:55 UTC, rafaelss requested changes

2020-09-08 14:55 UTC, rafaelss commented on app/services/total_express/status_reader.rb
> -
não precisaria mexer nesse linha

2020-09-08 16:32 UTC, cotelha commented on app/services/total_express/status_reader.rb
> -
@rafaelss não entendi a questão da linha!

E aproveitando no CI está dando um erro:
Your bundle is locked to codecov (0.1.14), but that version could not be found
Tenho que atualizar a Gem?

2020-09-08 17:07 UTC, rafaelss commented on app/services/total_express/status_reader.rb
> -
tu adicionou um "diff" no arquivo simplesmente por apagar uma linha que não tem impacto na implementação. isso só gera noise no git e é sempre bom evitarmos

2020-09-08 17:09 UTC, rafaelss commented on app/services/total_express/status_reader.rb
> -
e sobre o codecov, sim, precisa ser atualizado
mas pra isso vou te pedir pra criar um PR que configura o dependabot. pode usar o da api-v2 como referência: https://github.com/vnda/api_v2/blob/39a45035b4767a18ea9cd56d53dc15c845554adf/.github/dependabot.yml (pode ignorar a parte do `github-actions`

2020-09-08 17:18 UTC, cotelha commented on app/services/total_express/status_reader.rb
> -
@rafaelss sobre a linha em branco, entendido!
E preciso de acesso a api_v2 no github, que hj não tenho acesso.

2020-09-08 17:23 UTC, rafaelss commented on app/services/total_express/status_reader.rb
> -
https://gist.github.com/rafaelss/e8712582243fd8e05a741513b35d8cec

coloca ele na raiz da pasta `.github`

2020-09-08 19:38 UTC, rafaelss requested changes

2020-09-08 19:38 UTC, rafaelss commented on app/services/total_express/api.rb
> +    def cache_response_client
acho que seria melhor se fosse `cached_response`

2020-09-08 19:38 UTC, rafaelss commented on app/services/total_express/api.rb
> +          message: params_builder
esses parâmetros não mudam a cada request?

2020-09-08 19:38 UTC, rafaelss commented on spec/services/total_express/status_reader_spec.rb
> +      it 'returns status in exception' do
```suggestion
      it 'returns status as exception' do
```

2020-09-08 19:38 UTC, rafaelss commented on spec/services/total_express/status_reader_spec.rb
> +    context 'when order have more than a return in api' do
me parece que faz mais sentido se for:

```suggestion
    context 'when response have multiple orders' do
```

2020-09-08 20:29 UTC, cotelha commented on app/services/total_express/api.rb
> +          message: params_builder
O único parâmetro é a data atual, só vai mudar de um dia para o outro! Acha que pode ter algum problema aqui com os parâmetros?

2020-09-08 20:31 UTC, cotelha commented on spec/services/total_express/status_reader_spec.rb
> +      it 'returns status in exception' do
:+1:

2020-09-08 20:31 UTC, cotelha commented on spec/services/total_express/status_reader_spec.rb
> +    context 'when order have more than a return in api' do
:+1:

2020-09-08 20:31 UTC, cotelha commented on app/services/total_express/api.rb
> +    def cache_response_client
:+1:

2020-09-09 22:01 UTC, rafaelss approved these changes

2020-09-09 22:01 UTC, rafaelss commented on app/services/total_express/api.rb
> +          message: params_builder
talvez esse parametro pudesse fazer parte da chave do cache, mas podemos deixar assim por enquanto

2020-09-09 22:01 UTC, merged