Remove notification_url e refatora endpoints com a api_v2
vnda/vnda-tracker pull request #80
Opened 2020-09-21 23:59 UTC by cotelha

https://trello.com/c/60gF3QmR

2020-09-22 14:24 UTC, rafaelss commented
@cotelha rebase

2020-09-22 15:05 UTC, cotelha commented
@rafaelss feito!

2020-09-23 15:39 UTC, fdc263 requested changes

2020-09-23 15:39 UTC, fdc263 commented on app/models/shop.rb
> +  validates :slug, :name, :token, :api_url, presence: true
`host` é o nome adequado. O domínio (host) da loja

2020-09-23 15:39 UTC, fdc263 commented on app/views/shops/_form.html.erb
> +        <%= f.label :api_url %><br>
deixa o token antes do host

2020-09-23 15:39 UTC, fdc263 commented on app/views/shops/show.html.erb
> +  <dt class="col-sm-3">Endereço da api </dt>
Host da loja

2020-09-23 15:39 UTC, fdc263 commented on app/workers/notify.rb
> +      url: shop.api_url,
Aqui a ideia é guardar a URL completa da notificação. Tu pode tentar pegar do `res/response` que tem ali.

2020-09-23 15:39 UTC, fdc263 commented on app/workers/notify.rb
> +    res = Vnda::NotificationTracking.new(shop).dispatch(tracking)
```suggestion
    response = Vnda::NotificationTracking.new(shop).dispatch(tracking)
```

2020-09-23 15:39 UTC, fdc263 commented on spec/models/shop_spec.rb
> +    it { expect { shop } .to raise_error(ActiveRecord::RecordInvalid) }
"raises error"

2020-09-23 23:10 UTC, cotelha commented on app/models/shop.rb
> +  validates :slug, :name, :token, :api_url, presence: true
:+1:

2020-09-23 23:10 UTC, cotelha commented on app/views/shops/_form.html.erb
> +        <%= f.label :api_url %><br>
:+1:

2020-09-24 11:51 UTC, cotelha commented on app/views/shops/show.html.erb
> +  <dt class="col-sm-3">Endereço da api </dt>
:+1:

2020-09-24 11:53 UTC, cotelha commented on app/workers/notify.rb
> +      url: shop.api_url,
@fdc263 eu troquei pro res.host, mas acho que só pega o host também. não achei nenhum que método que pega a URI completa.

2020-09-24 11:53 UTC, cotelha commented on app/workers/notify.rb
> +    res = Vnda::NotificationTracking.new(shop).dispatch(tracking)
:+1:

2020-09-24 11:53 UTC, cotelha commented on spec/models/shop_spec.rb
> +    it { expect { shop } .to raise_error(ActiveRecord::RecordInvalid) }
:+1:

2020-10-06 17:26 UTC, fdc263 commented
rebase

2020-10-22 14:14 UTC, fdc263 approved these changes

2020-10-22 14:14 UTC, merged