Adiciona integração com o Melhor Envio
vnda/vnda-tracker pull request #81
Opened 2020-09-25 19:01 UTC by cotelha

https://trello.com/c/60gF3QmR

2020-09-29 18:12 UTC, gustavoreis commented
@cotelha ta aberto pra review aqui?

2020-09-29 18:20 UTC, cotelha commented
@gustavoreis tá liberado pra review!

2020-09-29 18:35 UTC, fdc263 requested changes

2020-09-29 18:35 UTC, fdc263 commented on app/services/melhor_envio.rb
> +  rescue Excon::Errors::Error => e
```suggestion
  rescue Excon::Errors::Error => exception
```

2020-09-29 18:35 UTC, fdc263 commented on app/services/melhor_envio.rb
> +    Honeybadger.notify(e, context: { tracking_code: tracking_code })
Escreve um teste em que a request retorne 500

2020-09-29 18:35 UTC, fdc263 commented on db/migrate/20200921232742_add_melhor_envio_to_shops.rb
> +    add_column :shops, :melhor_envio_enabled, :boolean
`default: :false`

2020-09-29 18:35 UTC, fdc263 commented on spec/services/melhor_envio_spec.rb
> +describe MelhorEnvio do
```suggestion
RSpec.describe MelhorEnvio do
```

2020-09-29 18:35 UTC, fdc263 commented on spec/services/melhor_envio_spec.rb
> +    )
```suggestion
    stub_request(:get, 'http://shop1.vnda.com.br/api/v2/shop')
      .to_return(
        status: 200,
        body: {
          settings: {
            melhor_envio_access_token: 'foo'
          }
        }.to_json
      )
```

2020-09-29 18:35 UTC, fdc263 commented on spec/services/melhor_envio_spec.rb
> +        .to_return(status: 200, body: response_with_event.to_json)
Ai sim!

2020-09-29 18:35 UTC, fdc263 commented on spec/services/vnda/shop_spec.rb
> +    )
```suggestion
    stub_request(:get, 'http://shop1.vnda.com.br/api/v2/shop')
      .to_return(
        status: 200,
        body: {
          settings: {
            melhor_envio_access_token: '123123'
          }
        }.to_json
      )
```

2020-10-06 18:18 UTC, cotelha commented on app/services/melhor_envio.rb
> +  rescue Excon::Errors::Error => e
:+1:

2020-10-06 20:18 UTC, cotelha commented on app/services/melhor_envio.rb
> +    Honeybadger.notify(e, context: { tracking_code: tracking_code })
:+1:

2020-10-06 20:18 UTC, cotelha commented on db/migrate/20200921232742_add_melhor_envio_to_shops.rb
> +    add_column :shops, :melhor_envio_enabled, :boolean
:+1:

2020-10-06 20:18 UTC, cotelha commented on spec/services/melhor_envio_spec.rb
> +describe MelhorEnvio do
:+1:

2020-10-06 20:18 UTC, cotelha commented on spec/services/melhor_envio_spec.rb
> +    )
:+1:

2020-10-06 20:18 UTC, cotelha commented on spec/services/melhor_envio_spec.rb
> +        .to_return(status: 200, body: response_with_event.to_json)
:+1:

2020-10-06 20:18 UTC, cotelha commented on spec/services/vnda/shop_spec.rb
> +    )
:+1:

2020-10-07 12:57 UTC, fdc263 approved these changes

2020-10-07 12:57 UTC, merged